### ISSUE TITLE
Task List Design

### ISSUE THREAD

**Issue by mohsinht** [taskbarter/main#10]
Hey @ahmadx16, you are doing an excellent job. I just wanted to suggest some enhancements.

- Show only 3 tasks on dashboard and make a button that says 'Show More'.
- 'Show More' will take the user to 'Explore' page. Here 10-15 tasks must be shown and rest must be paginated.
- Clicking on task will open up a modal like in upwork. It will show some info about the poster and the task.

**Comment by ahmdhsn-dev** [comment]
@mohsinht Ok

**Comment by mohsinht** [comment]
Done
