### ISSUE TITLE
Image Uploading - Profile Pic, Task Pictures etc.

### ISSUE THREAD

**Issue by mohsinht** [taskbarter/main#11]
Use Firebase for this purpose. They provide free 1gb storage and I think it'll be enough. If we could compress the images to at least 100kb, we can host 10,000 images on Firebase hosting.

- To crop/preview image, I will use this plugin: https://www.npmjs.com/package/react-image-crop
- For image compression on Express, I will use this plugin: https://www.npmjs.com/package/browser-image-compression
- After successful uploading, its URL will be saved in the MongoDB profile collection.

**Comment by mohsinht** [comment]
Just realized if I could use [Cloudinary](https://elements.heroku.com/addons/cloudinary) for image hosting. They provide **10GB** free storage and have image compression built-in.
Using Cloudinary, we can store more than 300,000 images.

**Comment by ahmdhsn-dev** [comment]
Hey @mohsinht . I want to work on this enhancement, Kindly update if there is any work that you have already done on this.

**Comment by mohsinht** [comment]
I think its complete, just integration is needed to be done. I'm just about to finish this feature in the next couple of commits.
I'll let you know if any thing else is needed in this feature.

**Comment by ahmdhsn-dev** [comment]
Ok, Great!

**Comment by mohsinht** [comment]
This option is skipped as we dont need images as yet.
